package day5;

public class ExceptionTest {

	public static void main(String[] args) {
		
		// 1. ArrayIndexOutOfBoundsException
		// args[0] = 100, args[1] = null
//		int i = Integer.parseInt(args[0]); // 
//		int j = Integer.parseInt(args[1]); //이 값이 없어서 ArrayIndexOutOfBoundsException
//		System.out.println(i/j);
//		System.out.println("main 종료");
		
		
		// 2. ArrayIndexOutOfBoundsException
		// args[0] = 100, args[1] = null
		int i = Integer.parseInt(args[0]); // 
		int j = Integer.parseInt(args[1]); //이 값이 없어서 ArrayIndexOutOfBoundsException
		System.out.println(i/j);
		System.out.println("main 종료");

	}

}
